
#ifndef SDL_WRAPPER_GRAPHICS_EXPORT_HPP
#define SDL_WRAPPER_GRAPHICS_EXPORT_HPP

#ifdef SDL_WRAPPER_GRAPHICS_STATIC_DEFINE
#  define SDL_WRAPPER_GRAPHICS_EXPORT
#  define SDL_WRAPPER_GRAPHICS_NO_EXPORT
#else
#  ifndef SDL_WRAPPER_GRAPHICS_EXPORT
#    ifdef SDL_wrapper_graphics_EXPORTS
        /* We are building this library */
#      define SDL_WRAPPER_GRAPHICS_EXPORT 
#    else
        /* We are using this library */
#      define SDL_WRAPPER_GRAPHICS_EXPORT 
#    endif
#  endif

#  ifndef SDL_WRAPPER_GRAPHICS_NO_EXPORT
#    define SDL_WRAPPER_GRAPHICS_NO_EXPORT 
#  endif
#endif

#ifndef SDL_WRAPPER_GRAPHICS_DEPRECATED
#  define SDL_WRAPPER_GRAPHICS_DEPRECATED __declspec(deprecated)
#endif

#ifndef SDL_WRAPPER_GRAPHICS_DEPRECATED_EXPORT
#  define SDL_WRAPPER_GRAPHICS_DEPRECATED_EXPORT SDL_WRAPPER_GRAPHICS_EXPORT SDL_WRAPPER_GRAPHICS_DEPRECATED
#endif

#ifndef SDL_WRAPPER_GRAPHICS_DEPRECATED_NO_EXPORT
#  define SDL_WRAPPER_GRAPHICS_DEPRECATED_NO_EXPORT SDL_WRAPPER_GRAPHICS_NO_EXPORT SDL_WRAPPER_GRAPHICS_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SDL_WRAPPER_GRAPHICS_NO_DEPRECATED
#    define SDL_WRAPPER_GRAPHICS_NO_DEPRECATED
#  endif
#endif

#endif /* SDL_WRAPPER_GRAPHICS_EXPORT_HPP */
